// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Doctor struct {
	ID       string
	Name     string
	Crm      string
	Birthday time.Time
	UserID   string
}

type Patient struct {
	ID       string
	Name     string
	Birthday time.Time
	UserID   string
}

type User struct {
	ID       string
	Password string
	Email    string
}
