// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"
	"time"
)

const createDoctor = `-- name: CreateDoctor :exec
INSERT INTO doctors (id, name,crm ,birthday, user_id)
VALUES ($1, $2, $3, $4,$5)
`

type CreateDoctorParams struct {
	ID       string
	Name     string
	Crm      string
	Birthday time.Time
	UserID   string
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) error {
	_, err := q.db.ExecContext(ctx, createDoctor,
		arg.ID,
		arg.Name,
		arg.Crm,
		arg.Birthday,
		arg.UserID,
	)
	return err
}

const createPatient = `-- name: CreatePatient :exec
INSERT INTO patients (id, name, birthday, user_id)
VALUES ($1, $2, $3, $4)
`

type CreatePatientParams struct {
	ID       string
	Name     string
	Birthday time.Time
	UserID   string
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) error {
	_, err := q.db.ExecContext(ctx, createPatient,
		arg.ID,
		arg.Name,
		arg.Birthday,
		arg.UserID,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id,email, password)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	ID       string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.Password)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password 
FROM users 
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID       string
	Email    string
	Password string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}
